Homework2/Models/ErrorViewModel.cs
using System;

namespace Homework2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Homework2/Models/FormModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Homework2.Models
{
    public class FormModel
    {
        public int _counter;

        [Display(Name = "Imię")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Ilość powtórzeń")]
        public int Counter 
        { 
            get => _counter;
            set
            {
                if (value > 5 || value <= 0)
                    throw new System.ArgumentOutOfRangeException();
                else
                    _counter = value;
            }
        }
    }
}

Homework2/Controllers/FormController.cs
using Homework2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Homework2.Controllers
{
    public class FormController : Controller
    {
        public IActionResult Input()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Input(FormModel model)
        {
            if (ModelState.IsValid)
            {
                return View("Output", model);
            }
            return View(model);
        }
    }
}

Homework2/Controllers/HomeController.cs
using Homework2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Homework2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Homework2/Views/Form/Input.cshtml
@model Homework2.Models.FormModel
@{
    ViewData["Title"] = "Formularz";
}

<h1 class="display-4">@ViewData["Title"]</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Form" asp-action="Input" method="post">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Counter" class="control-label"></label>
                <input asp-for="Counter" class="form-control" placeholder="1..5"/>
                <span asp-validation-for="Counter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Wyślij" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Homework2/Views/Form/Output.cshtml
@model Homework2.Models.FormModel
@{
    ViewData["Title"] = "Wynik Formularza";
}

<div class="text-left">
    <h1 class="display-4">Dane z formularza</h1>
    @for (int i = 0; i < Model.Counter; i++)
    {
        <p>@Html.DisplayFor(model => model.Name)</p>
    }
</div>

Homework2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Homework2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Homework2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Homework2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Form" asp-action="Input">Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Homework2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>